# Generated by Django 4.2.17 on 2024-12-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="menu_images/"),
        ),
    ]
