# Generated by Django 4.2.17 on 2024-12-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="ordered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="ordered",
            field=models.BooleanField(default=False),
        ),
    ]
