# Generated by Django 4.2.17 on 2024-12-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0002_menuitem_image"),
        ("orders", "0004_alter_orderitem_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.AddField(
            model_name="order",
            name="order_items",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="cart", to="menus.menuitem"
            ),
        ),
    ]
