# Generated by Django 4.2.17 on 2024-12-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_remove_orderitem_order_order_order_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="table_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
